# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'W4D4-RealmDB' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for W4D4-RealmDB
  pod 'RealmSwift', '~> 3.0'
  
end
